### ISSUE TITLE
iOS용 앱에서 오른쪽 상단 자물쇠를 누르면 종료됩니다. In the app for iOS, click the upper right pad to exit.

### ISSUE THREAD

**Issue by munggo** [toscoin-project/toswallet-ios#2]
iOS용 앱에서 오른쪽 상단 자물쇠를 누르면 종료됩니다.

따라서 보낼 코인을 보낼 수 없습니다.

In the app for iOS, click the upper right pad to exit.

Therefore, you can not send a coin to send.

**Comment by ghbrylee** [comment]
Thank you for your patience. We've updated new version that fixed the issue for Face ID on the iPhoneX. We will release a new version on the official website as soon as possible.
